services:
  - type: static
    name: portfolio
    rootDir: portfolio-main
    staticPublicPath: /build
    buildCommand: cd portfolio-main && npm install && npm run build
    publishPath: portfolio-main/build
    routes:
      - path: /*
        destination: /index.html
